### ISSUE TITLE
老师，请教一个问题

### ISSUE THREAD

**Issue by 2qq2qq** [Grewer/android-casing-webapp#1]
我只是想做一个app，实现：
调用一个最简单的网页（不需要上传之类的），然后按返回键不退出，依旧在后台呆着。
按返回键后，表单输入的内容在下次打开这个app时依旧在（类似于微信）。
希望整个app体积不超过10K，在后台不大量耗内存。

我看了老师的文章，没做成功。
老师能帮我吗？谢谢你。

**Comment by Grewer** [comment]
很抱歉, 不知道为什么, 没收到过这个信息
今天有空浏览了下旧项目才发现
现在你应该没什么问题了吧
